# Generated by Django 5.1.4 on 2025-01-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='restaurant_id',
            new_name='lead_id',
        ),
    ]
