# Generated by Django 5.1.4 on 2025-01-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='restaurant_id',
            new_name='lead_id',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='name',
            new_name='restaurant_name',
        ),
    ]
