# Generated by Django 5.1.4 on 2025-01-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_restaurant_id_lead_lead_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='account_id',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
    ]
