# Generated by Django 5.1.4 on 2025-01-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KAM',
            fields=[
                ('kam_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=15, unique=True)),
                ('account_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'KAM',
                'verbose_name_plural': 'KAMs',
            },
        ),
    ]
