# Generated by Django 5.1.4 on 2025-01-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallSync',
            fields=[
                ('call_id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('restaurant_id', models.CharField(max_length=50)),
                ('scheduled_date', models.DateTimeField()),
                ('last_called', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'CallSync',
                'verbose_name_plural': 'CallSyncs',
            },
        ),
    ]
