# Generated by Django 5.1.4 on 2025-01-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsyncs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callsync',
            old_name='restaurant_id',
            new_name='lead_id',
        ),
        migrations.AddField(
            model_name='callsync',
            name='timezone',
            field=models.CharField(default='IST', max_length=20),
        ),
    ]
