# Generated by Django 5.1.4 on 2025-01-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('interaction_id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('restaurant_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
            },
        ),
    ]
