# Generated by Django 5.1.4 on 2025-01-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='details',
            new_name='call_status',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='restaurant_id',
            new_name='lead_id',
        ),
        migrations.AddField(
            model_name='interaction',
            name='timezone',
            field=models.CharField(default='IST', max_length=20),
            preserve_default=False,
        ),
    ]
